---
apiVersion: v1
kind: Secret
metadata:
  name: test-config
stringData:
  config.yml: |
    web:
      port: "3000"
      user: webadmin
      pass: password
    db:
      port: "5432"
      host: database
      name: mydb
      user: user
      pass: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scw-test-app
  name: scw-test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scw-test-app
  template:
    metadata:
      labels:
        app: scw-test-app
    spec:
      containers:
      - image: ghcr.io/n-arno/scw-test-app:latest
        name: scw-test-app
        volumeMounts:
        - name: config
          mountPath: "/config.yml"
          subPath: config.yml
      volumes:
      - name: config
        secret:
          secretName: test-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: scw-test-app
  name: scw-test-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: scw-test-app
  type: LoadBalancer
